export const INCREASE_COUNTER = "INCREASE_COUNTER"
export const DECREASE_COUNTER = "DECREASE_COUNTER"
export const INCREASE_BY_TWO_COUNTER = "INCREASE_BY_TWO_COUNTER"
export const DECREASE_BY_TWO_COUNTER = "DECREASE_BY_TWO_COUNTER"
